# CSE 25 Discussion 2 Notebook
## Lists, Dictionaries, NumPy, Pandas, and scikit-learn

This notebook provides guided practice with Python fundamentals that are important for upcoming machine learning workflows.

By the end, you will practice:
- Accessing and modifying lists
- Iterating with loops and list comprehensions
- Working with dictionaries
- Using NumPy for array operations
- Using Pandas DataFrames for filtering, grouping, and sorting
- Running a basic scikit-learn classification workflow

This notebook is optional and not required for submission.

In [1]:
# Helper
# assert is a function that tests if a condition is true. If the condition is false, it raises an AssertionError with an optional message.
# The syntax for assert is:
# assert condition, message


In [2]:
assert 1 + 1 == 2, "Math is broken!"

In [3]:
assert 1 + 2 == 2, "This will raise an AssertionError because 1 + 2 is not equal to 2."

AssertionError: This will raise an AssertionError because 1 + 2 is not equal to 2.

## 1. Lists

Lists are ordered, mutable collections that can hold different data types. You can initialize lists in multiple different ways.

In [4]:
# Creating lists
numbers = [1, 2, 3, 4, 5]
mixed = [1, "hello", 3.14, True]
empty = []
repeating = [1]*5
lst_of_lsts = [[1,2,3],[1]]

print("Numbers:", numbers)
print("Mixed types:", mixed)
print("Repeating", repeating)
print("list of lists:", lst_of_lsts)

Numbers: [1, 2, 3, 4, 5]
Mixed types: [1, 'hello', 3.14, True]
Repeating [1, 1, 1, 1, 1]
list of lists: [[1, 2, 3], [1]]


You can generally access element(s) of a list via lst[x] where x can be a singular number of multiple. lst[-1] gives the last element in the list. In lst_of_lsts, each element is a separate list.

**Exercise: Using [] to access list elements**

In [5]:
# Accessing elements (indexing starts at 0)
fruits = ["apple", "banana", "cherry", "date"]
lst_of_lsts = [[1,2,3],[1]]

first_fruit = fruits[0]
assert first_fruit == "apple", "Expected 'apple'"
print("First fruit:", fruits[0])

last_fruit = fruits[-1]
assert last_fruit == "date", "Expected 'date'"
print("Last fruit:", fruits[-1])

second_and_third = fruits[1:3]
assert second_and_third == ["banana", "cherry"], "Expected ['banana', 'cherry']"
print("Second and third:", second_and_third)

first_list = lst_of_lsts[0]
assert first_list == [1,2,3], "Expected [1,2,3]"
print("First list:", first_list)

First fruit: apple
Last fruit: date
Second and third: ['banana', 'cherry']
First list: [1, 2, 3]


You can add an object to the list by using .append

In [6]:
# Modifying lists
fruits.append("elderberry")  # Add to end
print("After append:", fruits)

After append: ['apple', 'banana', 'cherry', 'date', 'elderberry']


There are several commonly used list operations

In [7]:
# List operations
numbers = [3, 1, 4, 1, 5, 9, 2, 6]

print("Length:", len(numbers))
print("Sum:", sum(numbers))
print("Max:", max(numbers))
print("Min:", min(numbers))
print("Sorted:", sorted(numbers))
print("Reversed:", list(reversed(numbers)))

Length: 8
Sum: 31
Max: 9
Min: 1
Sorted: [1, 1, 2, 3, 4, 5, 6, 9]
Reversed: [6, 2, 9, 5, 1, 4, 1, 3]


We can iterate through the list with multiple ways

As the firt way, we can iterate by indexing.

In [8]:
list_length = len(numbers)
for index in range(list_length):
    print(f"Index {index}: {numbers[index]}")

Index 0: 3
Index 1: 1
Index 2: 4
Index 3: 1
Index 4: 5
Index 5: 9
Index 6: 2
Index 7: 6


As the second way, we can iterate in a **more pythonic way**.

In [9]:
for num in numbers:
    print(num)

3
1
4
1
5
9
2
6


**Exercise: Now let's see how we can get the even numbers from the list**

In [10]:
evens = []
for num in numbers:
    if num % 2 == 0:
        evens.append(num)

# Insert your code here

assert evens == [4, 2, 6], f"Expected [4, 2, 6], but got {evens}"
print("Even numbers:", evens)

Even numbers: [4, 2, 6]


List comprehensions are a more concise way to store values in a list via loops.

In [11]:
# List comprehensions - powerful way to create lists

evens = [x for x in numbers if x % 2 == 0]
assert evens == [4, 2, 6], f"Expected [4, 2, 6], but got {evens}"
print("Even numbers (comprehension):", evens)

Even numbers (comprehension): [4, 2, 6]


**Exercise: Can you use list comprehensions to access the odd numbers in the list?**

In [12]:
odds = [x for x in numbers if x % 2 != 0]
assert odds == [3, 1, 1, 5, 9], f"Expected [3, 1, 1, 5, 9], but got {odds}"
print("Odd numbers (comprehension):", odds)

Odd numbers (comprehension): [3, 1, 1, 5, 9]


How can we iterate through two lists at the same time? 

In [13]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]

for x, y in zip(list1, list2):
    print(f"{x} paired with {y}")

1 paired with 6
2 paired with 7
3 paired with 8
4 paired with 9
5 paired with 10


## 2. Dictionaries

Dictionaries store key-value pairs and provide fast lookups. Note you can store multiple types of objects in dictionaries.

In [14]:
# Creating dictionaries
student = {
    "name": "Alice",
    "age": 20,
    "major": "Computer Science",
    "gpa": 3.8
}

print("Student:", student)
print("Name:", student["name"])
print("GPA:", student.get("gpa"))

Student: {'name': 'Alice', 'age': 20, 'major': 'Computer Science', 'gpa': 3.8}
Name: Alice
GPA: 3.8


In [15]:
# Modifying dictionaries
student["age"] = 21  # Update value
student["graduation_year"] = 2026  # Add new key-value pair
del student["gpa"]  # Remove key-value pair

print("Updated student:", student)

Updated student: {'name': 'Alice', 'age': 21, 'major': 'Computer Science', 'graduation_year': 2026}


In [16]:
# Dictionary methods
student = {"name": "Bob", "age": 19, "major": "AI"}

print("Keys:", student.keys())
print("Values:", student.values())
print("Items:", student.items())

Keys: dict_keys(['name', 'age', 'major'])
Values: dict_values(['Bob', 19, 'AI'])
Items: dict_items([('name', 'Bob'), ('age', 19), ('major', 'AI')])


In [17]:
# Iterating through dictionaries
for key, value in student.items():
    print(f"{key}: {value}")

name: Bob
age: 19
major: AI


### Exercise: Dictionaries
`student1_scores` is the score for student1. Based on `student1_scores`, can you create `student2_scores` so that each score of student2 is 10 point higher than student1?
Hint: using `.items()` method.

In [18]:
# Creating dictionaries
student1_scores = {
    "hw1_score": 85,
    "hw2_score": 90,
    "hw3_score": 78,
}

student2_scores = {}
for hw, score in student1_scores.items():
    student2_scores[hw] = score + 10

assert student2_scores["hw1_score"]  == 95, f"Expected 95, but got {student2_scores['hw1_score']}"
assert student2_scores["hw2_score"]  == 100, f"Expected 100, but got {student2_scores['hw2_score']}"
assert student2_scores["hw3_score"]  == 88, f"Expected 92, but got {student2_scores['hw3_score']}"



## 3. NumPy

NumPy is the fundamental package for numerical computing in Python. It provides powerful array operations essential for AI/ML. In general, you should try to use numpy over traditional lists as many operations can be vectorized, or when operations are being applied simultaneously. It may be helpful to think of numpy arrays as extensions to default python lists.

In [19]:
import numpy as np

# Creating arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print("1D array:", arr1)
print("2D array:\n", arr2)
print("Shape of arr2:", arr2.shape)
print("Data type:", arr1.dtype)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
Shape of arr2: (2, 3)
Data type: int64


In [20]:
# Array creation functions
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
range_arr = np.arange(0, 10, 2)  # Start, stop, step
linspace = np.linspace(0, 1, 5)  # 5 evenly spaced numbers from 0 to 1
random_arr = np.random.rand(3, 3)  # Random values between 0 and 1

print("Zeros:\n", zeros)
print("\nRange:", range_arr)
print("\nLinspace:", linspace)
print("\nRandom:\n", random_arr)

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Range: [0 2 4 6 8]

Linspace: [0.   0.25 0.5  0.75 1.  ]

Random:
 [[0.35248387 0.31895082 0.23092701]
 [0.60035749 0.24130901 0.71354197]
 [0.74186656 0.2920233  0.79796282]]


In [21]:
# Array operations (vectorized - much faster than loops!)
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("Addition:", a + b)
print("Multiplication:", a * b)
print("Square:", a ** 2)
print("Greater than 2:", a > 2)

Addition: [11 22 33 44]
Multiplication: [ 10  40  90 160]
Square: [ 1  4  9 16]
Greater than 2: [False False  True  True]


In [22]:
# Mathematical functions
data = np.array([1, 4, 9, 16, 25])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard deviation:", np.std(data))
print("Sum:", np.sum(data))
print("Square root:", np.sqrt(data))

Mean: 11.0
Median: 9.0
Standard deviation: 8.648699324175862
Sum: 55
Square root: [1. 2. 3. 4. 5.]


In [23]:
# Indexing and slicing
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print("Original matrix:\n", matrix)
print("\nElement at [1, 2]:", matrix[1, 2])
print("First row:", matrix[0, :])
print("Second column:", matrix[:, 1])
print("Submatrix:\n", matrix[0:2, 1:3])
print("Mean of each row:", np.mean(matrix, axis=1))
print("Mean of each column:", np.mean(matrix, axis=0))

Original matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element at [1, 2]: 7
First row: [1 2 3 4]
Second column: [ 2  6 10]
Submatrix:
 [[2 3]
 [6 7]]
Mean of each row: [ 2.5  6.5 10.5]
Mean of each column: [5. 6. 7. 8.]


In [24]:
# Reshaping arrays
arr = np.arange(12)
print("Original:", arr)
print("Reshaped (3x4):\n", arr.reshape(3, 4))
print("Reshaped (2x6):\n", arr.reshape(2, 6))

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped (2x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [25]:
# Matrix operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nMatrix multiplication (dot product):\n", np.dot(A, B))
print("\nTranspose of A:\n", A.T)

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

Matrix multiplication (dot product):
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]


### Exercise: NumPy
Create a 5x5 matrix 
```Python
[
    [ 0,  1,  2,  3,  4],
    [ 5,  6,  7,  8,  9],
    [10, 11, 12, 13, 14],
    [15, 16, 17, 18, 19],
    [20, 21, 22, 23, 24]
]
```


In [26]:
# Hint first use arange to create a 1D array of length 25, then reshape it to a 5x5 matrix
matrix = np.arange(25).reshape(5, 5)
assert matrix.shape == (5, 5), f"Expected shape (5, 5), but got {matrix.shape}"
print("Matrix:\n", matrix)

Matrix:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Then calculate the mean of each row:

In [27]:
# Hint: use np.mean() with axis parameter to compute the mean of each row

mean_rows = np.mean(matrix, axis=1)

assert np.allclose(mean_rows, [2.0, 7.0, 12.0, 17.0, 22.0]), f"Expected [2.0, 7.0, 12.0, 17.0, 22.0], but got {mean_rows}"

print("Mean of each row:", mean_rows)

Mean of each row: [ 2.  7. 12. 17. 22.]


## Pandas:

We will cover:

1. **DataFrames**
2. **Filtering**
3. **Grouping**
4. **Sorting**

Each section includes an exercise to test your understanding.

In [28]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "major": ["Math", "CS", "Math", "Biology", "CS"],
    "score": [88, 95, 79, 91, 84]
})

df

,name,major,score
0,Alice,Math,88
1,Bob,CS,95
2,Charlie,Math,79
3,Diana,Biology,91
4,Eve,CS,84


### 1. DataFrames

A DataFrame is a table with rows and columns.

Useful operations:
- `df.shape`
- `df.columns`
- `df["col"]`
- `df[["col1", "col2"]]`

In [29]:
print(df.shape)
print(df.columns)
print(df["name"])
print(df[["name", "score"]])

(5, 3)
Index(['name', 'major', 'score'], dtype='str')
0      Alice
1        Bob
2    Charlie
3      Diana
4        Eve
Name: name, dtype: str
      name  score
0    Alice     88
1      Bob     95
2  Charlie     79
3    Diana     91
4      Eve     84


In [30]:
# Exercise 1

num_rows, num_cols = df.shape
data_names_and_scores = df[["name", "score"]]

assert num_rows == 5
assert num_cols == 3
assert list(data_names_and_scores.columns) == ["name", "score"]

print("Exercise 1 passed.")

Exercise 1 passed.


### 2. Filtering

Filtering selects rows that satisfy a condition.

Examples:
- `df[df["score"] > 90]`
- `df[df["major"] == "CS"]`
- `df[(cond1) & (cond2)]`

In [31]:
print(df[df["score"] > 90])
print(df[df["major"] == "CS"])
print(df[(df["major"] == "CS") & (df["score"] > 90)])

    name    major  score
1    Bob       CS     95
3  Diana  Biology     91
  name major  score
1  Bob    CS     95
4  Eve    CS     84
  name major  score
1  Bob    CS     95


In [32]:
# Exercise 2

students_with_cs_major = df[df["major"] == "CS"]
students_with_90_more_score = df[df["score"] > 90]

assert list(students_with_cs_major["name"]) == ["Bob", "Eve"]
assert list(students_with_90_more_score["name"]) == ["Bob", "Diana"]

print("Exercise 2 passed.")

Exercise 2 passed.


### 3. Grouping

`groupby` helps summarize data by category.

Examples:
- `df.groupby("major")["score"].mean()`
- `df.groupby("major")["name"].count()`

In [33]:
print(df.groupby("major")["score"].mean())
print(df.groupby("major")["name"].count())

major
Biology    91.0
CS         89.5
Math       83.5
Name: score, dtype: float64
major
Biology    1
CS         2
Math       2
Name: name, dtype: int64


In [34]:
# Exercise 3

mean_scores = df.groupby("major")["score"].mean()
counts = df.groupby("major")["name"].count()

assert round(mean_scores["Biology"], 2) == 91.00
assert round(mean_scores["CS"], 2) == 89.50
assert counts["Math"] == 2

print("Exercise 3 passed.")

Exercise 3 passed.


### 4. Sorting

Use `sort_values` to order rows.

Examples:
- `df.sort_values("score")`
- `df.sort_values("score", ascending=False)`
- `df.sort_values(["major", "score"])`

In [35]:
print(df.sort_values("score"))
print(df.sort_values("score", ascending=False))

      name    major  score
2  Charlie     Math     79
4      Eve       CS     84
0    Alice     Math     88
3    Diana  Biology     91
1      Bob       CS     95
      name    major  score
1      Bob       CS     95
3    Diana  Biology     91
0    Alice     Math     88
4      Eve       CS     84
2  Charlie     Math     79


In [36]:
# Exercise 4

sorted_df_with_asending_order = df.sort_values("score", ascending=True)

assert list(sorted_df_with_asending_order["name"]) == ['Charlie', 'Eve', 'Alice', 'Diana', 'Bob']

print("Exercise 4 passed.")

Exercise 4 passed.


## scikit-learn Basics

Topics:
- train/test split
- create a model
- fit a model
- predict
- compute accuracy

Each part has a short exercise with `assert` checks.

In [37]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

### 1. Load Data

We will use the Iris dataset.

- `X` stores the input features
- `y` stores the labels

In [38]:
iris = load_iris()
X = iris.data
y = iris.target

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Class names:", iris.target_names)

X shape: (150, 4)
y shape: (150,)
Class names: ['setosa' 'versicolor' 'virginica']


### 2. Train/Test Split

We split the dataset into:
- training data: used to learn
- test data: used to evaluate

Common function:
- `train_test_split(X, y, test_size=..., random_state=...)`

In [39]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training set size:", X_train.shape, y_train.shape)
print("Test set size:", X_test.shape, y_test.shape)

Training set size: (120, 4) (120,)
Test set size: (30, 4) (30,)


In [40]:
# Exercise 1
# Split with test_size of 0.1

Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.1, random_state=42)

assert Xtr.shape[0] == 135
assert Xte.shape[0] == 15
assert ytr.shape[0] == 135
assert yte.shape[0] == 15

print("Exercise 1 passed.")

Exercise 1 passed.


### 3. Create a Model

A model is created by calling its class.

Example:
- `DecisionTreeClassifier()`

In [41]:
model = DecisionTreeClassifier(random_state=42)
model

,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.",'gini'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... note:: The search for a split does not stop until at least one valid partition of the node samples is found, even if it requires to effectively inspect more than ``max_features`` features.",None
,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary ` for details.",42
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow a tree with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current

In [42]:
# Exercise 2

my_model = DecisionTreeClassifier(random_state=42)

assert isinstance(my_model, DecisionTreeClassifier)

print("Exercise 2 passed.")

Exercise 2 passed.


### 4. Fit the Model

`fit` trains the model using the training data.

- `model.fit(X_train, y_train)`

In [43]:
model.fit(X_train, y_train)
print("Model trained.")

Model trained.


In [44]:
# Exercise 3
# Fit and predict on Xtr 

# Your code here
my_model.fit(Xtr, ytr)

pred_tr = my_model.predict(Xtr)

assert len(pred_tr) == len(ytr)

print("Exercise 3 passed.")

Exercise 3 passed.


### 5. Predict

After training, we can use the model to predict labels.

- `model.predict(X_test)`

In [45]:
y_pred = model.predict(X_test)

print("Predictions:", y_pred[:10])
print("True labels:", y_test[:10])

Predictions: [1 0 2 1 1 0 1 2 1 1]
True labels: [1 0 2 1 1 0 1 2 1 1]


In [46]:
# Exercise 4
# Predict on Xte
pred_te = my_model.predict(Xte)

assert len(pred_te) == len(yte)

print("Exercise 4 passed.")

Exercise 4 passed.


### 6. Compute Accuracy

Accuracy is the fraction of correct predictions.

Two common ways:
- `accuracy_score(y_test, y_pred)`
- `model.score(X_test, y_test)`

In [47]:
acc1 = accuracy_score(y_test, y_pred)
acc2 = model.score(X_test, y_test)

print("Accuracy with accuracy_score:", acc1)
print("Accuracy with model.score:", acc2)

Accuracy with accuracy_score: 1.0
Accuracy with model.score: 1.0


In [48]:
# Exercise 5
# Calculate accuracy between pred_te and yte

acc = accuracy_score(yte, pred_te)

assert 0.8 <= acc <= 1.0
print(f"Accuracy: {acc:.2f}")
print("Exercise 5 passed.")

Accuracy: 1.00
Exercise 5 passed.


## Summary

In this discussion notebook, you practiced core Python and data science tools used in machine learning workflows:

- Lists: indexing, slicing, loops, and list comprehensions
- Dictionaries: key-value access, updates, and iteration
- NumPy: array creation, reshaping, slicing, and vectorized operations
- Pandas: DataFrame inspection, filtering, grouping, and sorting
- scikit-learn: loading data, train/test split, model training, prediction, and accuracy evaluation

If all `assert` checks pass, your implementations are working correctly.
