# CSE 25 Discussion 2 Notebook
## Lists, Dictionaries, NumPy, and Matplotlib

This notebook is to help you practice more of the python fundamentals required for later machine learning workflows. It covers lists, list comphrensions, dictionaries, numpy, and matplotlib. It is not required for submission.

## 1. Lists

Lists are ordered, mutable collections that can hold different data types. You can initialize lists in multiple different ways.

In [19]:
# Creating lists
numbers = [1, 2, 3, 4, 5]
mixed = [1, "hello", 3.14, True]
empty = []
repeating = [1]*5
lst_of_lsts = [[1,2,3],[1]]

print("Numbers:", numbers)
print("Mixed types:", mixed)
print("Repeating", repeating)
print("list of lists:", lst_of_lsts)

Numbers: [1, 2, 3, 4, 5]
Mixed types: [1, 'hello', 3.14, True]
Repeating [1, 1, 1, 1, 1]
list of lists: [[1, 2, 3], [1]]


You can generally access element(s) of a list via lst[x] where x can be a singular number of multiple. lst[-1] gives the last element in the list. In lst_of_lsts, each element is a separate list.

In [21]:
# Accessing elements (indexing starts at 0)
fruits = ["apple", "banana", "cherry", "date"]
lst_of_lsts = [[1,2,3],[1]]

print("First fruit:", fruits[0])
print("Last fruit:", fruits[-1])
print("Second and third:", fruits[1:3])
print("First list", lst_of_lsts[0])

First fruit: apple
Last fruit: date
Second and third: ['banana', 'cherry']
First list [1, 2, 3]


There are multiple ways to insert or delete from a list.

In [25]:
# Modifying lists
fruits.append("elderberry")  # Add to end
fruits.insert(1, "apricot")  # Insert at position
fruits.remove("banana")      # Remove by value
popped = fruits.pop()        # Remove and return last item

print("Modified list:", fruits)
print("Popped item:", popped)

fruits += ["pineapple"] # appending lists together
strawberry = ['strawberry']
fruits += strawberry

print("fruits:", fruits)

Modified list: ['apple', 'apricot', 'cherry', 'date']
Popped item: elderberry
fruits: ['apple', 'apricot', 'cherry', 'date', 'pineapple', 'strawberry']


In [26]:
# List operations
numbers = [3, 1, 4, 1, 5, 9, 2, 6]

print("Length:", len(numbers))
print("Sum:", sum(numbers))
print("Max:", max(numbers))
print("Min:", min(numbers))
print("Sorted:", sorted(numbers))
print("Reversed:", list(reversed(numbers)))

Length: 8
Sum: 31
Max: 9
Min: 1
Sorted: [1, 1, 2, 3, 4, 5, 6, 9]
Reversed: [6, 2, 9, 5, 1, 4, 1, 3]


List comprehensions are a more concise way to store values in a list via loops.

In [32]:
# List comprehensions - powerful way to create lists

evens = [x for x in range(20) if x % 2 == 0]
ones = [1 for _ in range(10)]
squares = [x**2 for x in range(10)]

print("Even numbers:", evens)
print("Ones:", ones)
print("Squares:", squares)

squares_loop = []
for x in range(10):
    squares_loop += [x**2]

print("Squares loop:", squares_loop)

Even numbers: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
Ones: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Squares: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
Squares loop: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


### Exercise: Lists
Create a list of temperatures in Celsius and convert them to Fahrenheit using a list comprehension.

In [ ]:
# Your code here
celsius = [0, 10, 20, 30, 40]
# Formula: F = C * 9/5 + 32


## 2. Dictionaries

Dictionaries store key-value pairs and provide fast lookups. Note you can store multiple types of objects in dictionaries. For PA 2, you will be coding a feed forward neural network (FFNN) as a dictionary of lists and other objects.

In [33]:
# Creating dictionaries
student = {
    "name": "Alice",
    "age": 20,
    "major": "Computer Science",
    "gpa": 3.8
}

print("Student:", student)
print("Name:", student["name"])
print("GPA:", student.get("gpa"))

Student: {'name': 'Alice', 'age': 20, 'major': 'Computer Science', 'gpa': 3.8}
Name: Alice
GPA: 3.8


In [34]:
# Modifying dictionaries
student["age"] = 21  # Update value
student["graduation_year"] = 2026  # Add new key-value pair
del student["gpa"]  # Remove key-value pair

print("Updated student:", student)

Updated student: {'name': 'Alice', 'age': 21, 'major': 'Computer Science', 'graduation_year': 2026}


In [35]:
# Dictionary methods
student = {"name": "Bob", "age": 19, "major": "AI"}

print("Keys:", student.keys())
print("Values:", student.values())
print("Items:", student.items())

Keys: dict_keys(['name', 'age', 'major'])
Values: dict_values(['Bob', 19, 'AI'])
Items: dict_items([('name', 'Bob'), ('age', 19), ('major', 'AI')])


In [36]:
# Iterating through dictionaries
for key, value in student.items():
    print(f"{key}: {value}")

name: Bob
age: 19
major: AI


In [37]:
# Dictionary comprehensions
squares_dict = {x: x**2 for x in range(6)}
print("Squares dictionary:", squares_dict)

# Filtering dictionary
scores = {"Alice": 85, "Bob": 92, "Charlie": 78, "Diana": 95}
high_scores = {name: score for name, score in scores.items() if score >= 90}
print("High scores:", high_scores)

Squares dictionary: {0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
High scores: {'Bob': 92, 'Diana': 95}


### Exercise: Dictionaries
Create a dictionary to count the frequency of words in a sentence.

In [ ]:
# Your code here
sentence = "the quick brown fox jumps over the lazy dog the fox"
# Hint: Use split() and a loop or dictionary comprehension


## 3. NumPy

NumPy is the fundamental package for numerical computing in Python. It provides powerful array operations essential for AI/ML. In general, you should try to use numpy over traditional lists as many operations can be vectorized, or when operations are being applied simultaneously. It may be helpful to think of numpy arrays as extensions to default python lists.

In [45]:
import numpy as np

# Creating arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print("1D array:", arr1)
print("2D array:\n", arr2)
print("Shape of arr2:", arr2.shape)
print("Data type:", arr1.dtype)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
Shape of arr2: (2, 3)
Data type: int64


In [46]:
# Array creation functions
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
range_arr = np.arange(0, 10, 2)  # Start, stop, step
linspace = np.linspace(0, 1, 5)  # 5 evenly spaced numbers from 0 to 1
random_arr = np.random.rand(3, 3)  # Random values between 0 and 1

print("Zeros:\n", zeros)
print("\nRange:", range_arr)
print("\nLinspace:", linspace)
print("\nRandom:\n", random_arr)

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Range: [0 2 4 6 8]

Linspace: [0.   0.25 0.5  0.75 1.  ]

Random:
 [[0.69243603 0.26941233 0.24412552]
 [0.16829104 0.21876422 0.558102  ]
 [0.40383617 0.06489225 0.25391541]]


In [47]:
# Array operations (vectorized - much faster than loops!)
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("Addition:", a + b)
print("Multiplication:", a * b)
print("Square:", a ** 2)
print("Greater than 2:", a > 2)

Addition: [11 22 33 44]
Multiplication: [ 10  40  90 160]
Square: [ 1  4  9 16]
Greater than 2: [False False  True  True]


In [48]:
# Mathematical functions
data = np.array([1, 4, 9, 16, 25])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard deviation:", np.std(data))
print("Sum:", np.sum(data))
print("Square root:", np.sqrt(data))

Mean: 11.0
Median: 9.0
Standard deviation: 8.648699324175862
Sum: 55
Square root: [1. 2. 3. 4. 5.]


In [49]:
# Indexing and slicing
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print("Original matrix:\n", matrix)
print("\nElement at [1, 2]:", matrix[1, 2])
print("First row:", matrix[0, :])
print("Second column:", matrix[:, 1])
print("Submatrix:\n", matrix[0:2, 1:3])

Original matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element at [1, 2]: 7
First row: [1 2 3 4]
Second column: [ 2  6 10]
Submatrix:
 [[2 3]
 [6 7]]


In [50]:
# Reshaping arrays
arr = np.arange(12)
print("Original:", arr)
print("Reshaped (3x4):\n", arr.reshape(3, 4))
print("Reshaped (2x6):\n", arr.reshape(2, 6))

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped (2x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [51]:
# Matrix operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nMatrix multiplication (dot product):\n", np.dot(A, B))
print("\nTranspose of A:\n", A.T)

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

Matrix multiplication (dot product):
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]


### Exercise: NumPy
Create a 5x5 matrix of random integers between 1 and 100, then find the mean of each row.

In [52]:
# Your code here
# Hint: Use np.random.randint() and np.mean() with axis parameter


## Summary

In this notebook, we covered:

1. **Lists**: Ordered, mutable collections with powerful comprehension syntax
2. **Dictionaries**: Key-value pairs for fast lookups and data organization
3. **NumPy**: Efficient numerical operations and array manipulation for AI/ML
4. **Matplotlib**: Data visualization for understanding patterns and relationships